# Generated by Django 2.0.7 on 2019-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_id', models.CharField(default='default', max_length=200)),
                ('nbr_lamp', models.IntegerField(default=0)),
                ('year_eco', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('gain_eco', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='default', max_length=200)),
            ],
        ),
    ]
